# Generated by Django 5.1.6 on 2025-02-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='MinMaxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('min_humidity', models.FloatField()),
                ('max_humidity', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
            ],
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uptime_ms', models.BigIntegerField()),
                ('free_heap', models.IntegerField()),
                ('wifi_strength', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
            ],
        ),
    ]
