# Generated by Django 5.1.6 on 2025-02-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_weatherdata_timestamp_minmaxdata_systemstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='station_id',
            new_name='station_ref',
        ),
    ]
