# Generated by Django 5.1.6 on 2025-02-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_station_id_station_station_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='http_address',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
